### ISSUE TITLE
Script failures if GPS doesn't yet have valid signal lock

### ISSUE THREAD

**Issue by TopperBG** [stevieb9/gpsd-parse#9]
OS: Debian 9.7
Uname: Linux var-som-mx6 4.9.11-02308-g86c54d808ad9-dirty #28 SMP PREEMPT Wed Dec 5 08:38:39 EST 2018 armv7l GNU/Linux

```
perl --version
This is perl 5, version 24, subversion 1 (v5.24.1) built for arm-linux-gnueabihf-thread-multi-64int
(with 81 registered patches, see perl -V for more detail)
```

**The install ends with failed tests:**
`Test Summary Report
-------------------
t/15-device.t            (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/20-tpv.t               (Wstat: 3328 Tests: 39 Failed: 13)
  Failed tests:  2, 6-9, 12-14, 16-17, 19-21
  Non-zero exit status: 13
t/30-sky.t               (Wstat: 2816 Tests: 16 Failed: 11)
  Failed tests:  2, 4-10, 12, 15-16
  Non-zero exit status: 11
Files=17, Tests=176,  5 wallclock secs ( 0.44 usr  0.09 sys +  4.55 cusr  0.34 csys =  5.42 CPU)
Result: FAIL
Failed 3/17 test programs. 25/176 subtests failed.
Makefile:832: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
  STEVEB/GPSD-Parse-1.02.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports STEVEB/GPSD-Parse-1.02.tar.gz`

**Comment by TopperBG** [comment]
Clone repo, changed in 15-device.t line 27 to:
`like $t, qr|^/dev/tty$|, "...and is ok";`
because my device is /dev/ttymxc3
Able to install manual the module
But now have another error:

> Use of uninitialized value $lat in pattern match (m//) at /usr/local/share/perl/5.24.1/GPSD/Parse.pm line 185, <GEN0> line 4.

Edit: If I stop services gpsd and gpsd.socket I'm able to install it trough cpan install and it's ok.
I'm using that script for test https://metacpan.org/source/STEVEB/GPSD-Parse-1.02/examples/gps.pl
With running GPSD and socket, but don't have a 2D/3D lock yet and have next errors:

> Use of uninitialized value $lat in pattern match (m//) at /usr/local/share/perl/5.24.1/GPSD/Parse.pm line 185, <GEN0> line 4.
> Use of uninitialized value in concatenation (.) or string at gps-simple-test.pl line 10, <GEN0> line 4.

It's came in mind that if there isn't lock... the code won't work ?

**Comment by TopperBG** [comment]
Yes, that's the case - if there isn't GPS lock and there isn't live date parser won't work.

**Comment by stevieb9** [comment]
Thanks for the report and all of the testing, @TopperBG!

Clearly looks like I overlooked a couple of things in this distribution. As soon as I get a chance, I'll connect up one of my GPS units and have a good go over of the code, apply your fix, and then attempt to sort out where else I should be doing checks (for example, error out a bit cleaner if there's no live data).

**Comment by stevieb9** [comment]
The install problem is now corrected, so now I'll focus on adding a lock so that code doesn't throw warnings or errors if the GPS isn't triangulated yet. After that, I'll upload the new version to CPAN.
